### PR TITLE
Truncate long quote previews

### PR DESCRIPTION
**Pull request by neutrinog**
This is related to https://github.com/unfoldingWord-dev/translationCore/issues/5097.

* Long quotes are truncated in the menu and a square-ish tool-tip displaying all of the text appears when hovered.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/62)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@neutrinog I was not able to get the tool tip to show for some reason. Is it working on your end?

**Comment by neutrinog** [comment]
yes it was working well for me. I can double check on a few different OS' tomorrow.

**Comment by mannycolon** [comment]
@neutrinog I was able to get the tooltip but I can still see the text overflow to the right when I scroll to the right within the menu.

**Comment by neutrinog** [comment]
@mannycolon @RoyalSix can you confirm you took these steps when testing?

In the tc repo:
* `git checkout release-v1.0.2`
* `npm run load-apps`
* `npm ci`
* `npm i translationCoreApps/tc-ui-toolkit#bugfix/joel/5097/truncate-quotes`
* `npm start`

**Comment by neutrinog** [comment]
ok I tweaked the package.json so it should work to install from github on windows. I forgot I had some bash code in there which was breaking on windows.

I just tested the text truncation and the popover on linux, mac, and windows.

**Pull request merged**
