### PR TITLE
Feature mcleanb 3086/show invalidated selection

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- on verse edit, sets invalidation flag on any selections that are not longer valid in verse.
- on new selection, clears the invalidation flag for that selection
- on tw startup, verify all selections to make sure they are still valid.

#### Testing
- On local testing, should look like (when you hover over the superscript 1), and also note the invalidated icon:

screen shot 2018-05-22 at 12 07 40 pm

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/15)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @RoyalSix)

---

*[package.json, line 90 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/15#-LEmF2ID83InQulpEP0p:-LEmF2IE3Cvnc8VGLAPK:b5syocd) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/9e1f1643858d85e14b78e2b098fa5fc2433bea5c/package.json#L90)):*
> ```JSON
>     "jest-css-modules": "^1.1.0",
>     "jest-enzyme": "^6.0.0",
>     "material-ui": "^0.20.1",
> ```

this should not be added. we are using @material-ui/core now lookup their docs here https://material-ui.com/
https://github.com/mui-org/material-ui


This may be caused because you haven't merge with latest master branch

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/15)*

**Comment by mannycolon** [comment]
How come you published the new version without this PR being merge ?

we want to merge the PR before we publish the new version

**Comment by PhotoNomad0** [comment]
> How come you published the new version without this PR being merge ?
> 
> we want to merge the PR before we publish the new version

@mannycolon - Sorry, that was added to get unit tests to pass.  Don't need the themes anymore.

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/15)*

**Pull request merged**
