### PR TITLE
Group Menu & tHelps

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/10)

### CODE REVIEW

**Comment by RoyalSix** [comment]
https://github.com/unfoldingWord-dev/translationCore/issues/4313

**Comment by mannycolon** [comment]
@RoyalSix Resolve merge conflicts

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 10 of 27 files at r1, 7 of 9 files at r2, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/10#-:-LC5Pg6l3Ol769f_HXV_:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix Please Fix unit tests

**Comment by mannycolon** [comment]
Reviewed 3 of 48 files at r5, 39 of 50 files at r6, 6 of 7 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/10)*

**Pull request merged**
