### PR TITLE
Added missing features to scripture pane

### PR DESCRIPTION
**Pull request by mannycolon**
- Deleted build/ and added it to the `.gitignore` file so we avoid merge conflicts in the future

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 20 of 21 files at r1.
Review status: 20 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[package.json, line 10 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12#-LCCrnHH9ZViLrDDHLCs:-LCCrnHH9ZViLrDDHLCt:b-jbt2kj) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/2c59f4f26f6bf4ad9633d7496fff112f8e5dd616/package.json#L10)):*
> ```JSON
>     "start": "webpack --watch",
>     "build": "webpack",
>     "start-ui-renderer": "cd tc-ui-toolkit-test; npm start",
> ```

You will need to add a npm run build script to the pre install so that the build is always up to date

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by mannycolon** [comment]
Review status: 18 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 10 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12#-LCCrnHH9ZViLrDDHLCs:-LCFzeN23ujYdHkP-Tkz:b-896fix) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/2c59f4f26f6bf4ad9633d7496fff112f8e5dd616/package.json#L10)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

You will need to add a npm run build script to the pre install so that the build is always up to date
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by mannycolon** [comment]
Review status: 18 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 10 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12#-LCCrnHH9ZViLrDDHLCs:-LCFzkRu1yipFmZ-QSnC:be2do7b) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/2c59f4f26f6bf4ad9633d7496fff112f8e5dd616/package.json#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good catch !!

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 10 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12#-LCCrnHH9ZViLrDDHLCs:-LCUBYtH8MXOEF08RlyP:b-ur2mt4) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/2c59f4f26f6bf4ad9633d7496fff112f8e5dd616/package.json#L10)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Nice haha I was actually meaning to have it in the "prepublish" script so when the user installs it has the latest
</blockquote></details>

User as in the people actually using the ui-kit

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by mannycolon** [comment]
Review status: 16 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 10 at r1](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12#-LCCrnHH9ZViLrDDHLCs:-LCW2fLE7hF4zld9wYvb:b1oqtlr) ([raw file](https://github.com/translationcoreapps/tc-ui-toolkit/blob/2c59f4f26f6bf4ad9633d7496fff112f8e5dd616/package.json#L10)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

User as in the people actually using the ui-kit
</blockquote></details>

Don't quite understand what you mean

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by RoyalSix** [comment]
Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/12)*

**Comment by RoyalSix** [comment]
Nice job! It looks like when you have 3 panes only showing there is some spacing issues.
screen shot 2018-05-15 at 12 53 54 pm
I got here by deleting some panes and then switching the bookmark on / off to cause the app to re-render

**Comment by mannycolon** [comment]
@RoyalSix Just fixed the styling issue for the expanded scripture pane.

**Pull request merged**
